### ISSUE TITLE
Capture.png not defined

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [kavinjindal/Python-Calc#1]
Hi!

There is a error in your code as you have specified Capture.png but that image will not be existing in the Computer of the people who download your script!

Remove this line in your script and recompile it to exe 
`root.iconbitmap("D:/programming/Capture.PNG")`

**Comment by kavin-jindal** [comment]
Thanks for telling, I will update the code asap and also fix the further bugs

**Comment by Vedant-Bhalgama** [comment]
Good!
